name: CI-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      # Blazor Web
      - name: Restore Blazor Web
        run: dotnet restore ./Fahrtenbuch.Web/Fahrtenbuch.Web.csproj

      - name: Build Blazor Web
        run: dotnet build ./Fahrtenbuch.Web/Fahrtenbuch.Web.csproj --configuration Release --no-restore

      # MAUI
      - name: Restore MAUI
        run: dotnet restore ./Fahrtenbuch/Fahrtenbuch.csproj

      - name: Build MAUI
        run: dotnet build ./Fahrtenbuch/Fahrtenbuch.csproj --configuration Release --no-restore
