name: CI-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
      - name: Install .NET MAUI Build Tools
        run: dotnet workload install maui macos wasm-tools

      # Blazor Web
      - name: Restore Blazor Web
        run: dotnet restore ./Web/Web.csproj

      - name: Build Blazor Web
        run: dotnet build ./Web/Web.csproj --configuration Release --no-restore

      # Android
      - name: Restore Android
        run: dotnet restore ./MAUI/MAUI.csproj -f net9.0-android

      - name: Build Android
        run: dotnet build ./MAUI/MAUI.csproj -f net9.0-android --configuration Release --no-restore
